version: "2"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ~/data/discord/mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - ~/data/discord/redis:/data
    ports:
      - "6379:6379"
  ai:
    build: ./ai
    container_name: ai
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
  twitterbot:
    build: ./twitterbot
    container_name: twitterbot
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
  manager:
    build: ./manager
    container_name: manager
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - redis